
spring:
  application:
    name: tiny-store-auth-center
tuling:
    jwt:
      keyPairName: jwt.jks
      keyPairAlias: jwt
      keyPairSecret: 123123
      keyPairStoreSecret: 123123
server:
  port: 9998