server:
  port: 8866
spring:
  application:
    name: tiny-store-product
  redis:
    host: 192.168.59.252
    port: 6379
    password:   
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 50
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

seata:
  config:
    nacos:
      server-addr: 47.100.208.112:8848
    type: nacos
  registry:
    type: nacos
  tx-service-group: prex_tx_group
  client:
    support:
      spring:
        datasource-autoproxy: true

#zk配置
zk:
  curator:
    retryCount: 5 #重试次数
    elapsedTimeMs: 5000 #
    connectUrl: 47.100.208.112:2181 #zk地址
    sessionTimeOutMs: 60000 #会话超时时间
    connectionTimeOutMs: 5000 #连接超时时间